resource_group_name = "cst-myorg-azapp-dev-eastus-rg"
appservice_sku_name = "B1"
appservice_plan_name = "sample-asp"
appservice_name1 = "demoapp-d-azeast-ap"
appservice_os_type = "Linux"
docker_registry_server_url = "https://index.docker.io/pmadalia"