# This workflow will build a package using Maven and then publish it to JFrog Artifactory when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*'
      - '.github/workflows/ci.yml'

env:
  APPLICATION_NAME: demo-app
  APPLICATION_VERSION: v1.0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.1
        with:
          java-version: 17
          distribution: 'zulu'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
          run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker(Container Registry) Login
        if: contains('refs/heads/main', github.ref)
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USR }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          tags: ${ env.APPLICATION_NAME }/${ env.APPLICATION_NAME }:${ env.APPLICATION_VERSION }
## TODO:
# Implement Slack notification
# Implement Auto Deploy